version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

    healthcheck:
      test: [ "CMD", "bash", "-c", "</dev/tcp/localhost/8086" ]
      interval: '10s'
      timeout: '1s'
      retries: 5
      start_period: '10s'
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
      - --hostname-url=http://localhost:8086
      - --hostname-strict-https=false
      - --hostname-strict-backchannel=true
    volumes:
      - ./keycloak/alkurlevsky.json:/opt/keycloak/data/import/alkurlevsky.json
    ports:
      - '8086:8080'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge