version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - my_network

  redis:
    env_file: .env
    image: redis:7
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    volumes:
      - redis:/data
    networks:
      - my_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my_network

  selenium:
    container_name: remote_chromedriver
    image: seleniarm/standalone-chromium:121.0
    environment:
      - SE_OPTS=--session-timeout 3600
      - SE_VNC_NO_PASSWORD=true
    expose:
      - 4444
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres-db-volume:
    external: false
  redis:
    external: false
  pgadmin:
    external: false