# ------------------------------------------------------------------------
# Creates the examples database and respective user. This database location
# and access credentials are defined on the environment variables
# ------------------------------------------------------------------------
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${EXAMPLES_USER} WITH PASSWORD '${EXAMPLES_PASSWORD}';
  CREATE DATABASE ${EXAMPLES_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${EXAMPLES_DB} TO ${EXAMPLES_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${EXAMPLES_DB}" <<-EOSQL
   GRANT ALL ON SCHEMA public TO ${EXAMPLES_USER};
EOSQL

echo "Init airflow db"
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${AIRFLOW_USERNAME} WITH PASSWORD '${AIRFLOW_PASSWORD}';
  CREATE DATABASE airflow;
  GRANT ALL PRIVILEGES ON DATABASE airflow TO ${AIRFLOW_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "airflow" <<-EOSQL
   GRANT ALL ON SCHEMA public TO ${AIRFLOW_USERNAME};
EOSQL

echo "Init superset db"
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${SUPERSET_DATABASE_USER} WITH PASSWORD '${SUPERSET_DATABASE_PASSWORD}';
  CREATE DATABASE ${SUPERSET_DATABASE_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${SUPERSET_DATABASE_DB} TO ${SUPERSET_DATABASE_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${SUPERSET_DATABASE_DB}" <<-EOSQL
  GRANT ALL ON SCHEMA public TO ${SUPERSET_DATABASE_USER};
EOSQL

echo "Init huntflow db"
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER ${HUNTFLOW_DATABASE_USERNAME} WITH PASSWORD '${HUNTFLOW_DATABASE_PASSWORD}';
  CREATE DATABASE ${HUNTFLOW_DATABASE_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${HUNTFLOW_DATABASE_DB} TO ${HUNTFLOW_DATABASE_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${HUNTFLOW_DATABASE_DB}" <<-EOSQL
  GRANT ALL ON SCHEMA public TO ${HUNTFLOW_DATABASE_USERNAME};
EOSQL
